// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: PATH/company_svc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseAnswers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Company       *NewCompany            `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseAnswers) Reset() {
	*x = ResponseAnswers{}
	mi := &file_PATH_company_svc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseAnswers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAnswers) ProtoMessage() {}

func (x *ResponseAnswers) ProtoReflect() protoreflect.Message {
	mi := &file_PATH_company_svc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAnswers.ProtoReflect.Descriptor instead.
func (*ResponseAnswers) Descriptor() ([]byte, []int) {
	return file_PATH_company_svc_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseAnswers) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResponseAnswers) GetCompany() *NewCompany {
	if x != nil {
		return x.Company
	}
	return nil
}

type RequestVariables struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Contact       string                 `protobuf:"bytes,2,opt,name=contact,proto3" json:"contact,omitempty"`
	Website       string                 `protobuf:"bytes,3,opt,name=website,proto3" json:"website,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	Zip           string                 `protobuf:"bytes,7,opt,name=zip,proto3" json:"zip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVariables) Reset() {
	*x = RequestVariables{}
	mi := &file_PATH_company_svc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVariables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVariables) ProtoMessage() {}

func (x *RequestVariables) ProtoReflect() protoreflect.Message {
	mi := &file_PATH_company_svc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVariables.ProtoReflect.Descriptor instead.
func (*RequestVariables) Descriptor() ([]byte, []int) {
	return file_PATH_company_svc_proto_rawDescGZIP(), []int{1}
}

func (x *RequestVariables) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestVariables) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *RequestVariables) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *RequestVariables) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RequestVariables) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *RequestVariables) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RequestVariables) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

type NewCompany struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Contact       string                 `protobuf:"bytes,3,opt,name=contact,proto3" json:"contact,omitempty"`
	Website       string                 `protobuf:"bytes,4,opt,name=website,proto3" json:"website,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	State         string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	Zip           string                 `protobuf:"bytes,8,opt,name=zip,proto3" json:"zip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewCompany) Reset() {
	*x = NewCompany{}
	mi := &file_PATH_company_svc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewCompany) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewCompany) ProtoMessage() {}

func (x *NewCompany) ProtoReflect() protoreflect.Message {
	mi := &file_PATH_company_svc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewCompany.ProtoReflect.Descriptor instead.
func (*NewCompany) Descriptor() ([]byte, []int) {
	return file_PATH_company_svc_proto_rawDescGZIP(), []int{2}
}

func (x *NewCompany) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *NewCompany) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewCompany) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *NewCompany) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *NewCompany) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *NewCompany) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *NewCompany) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *NewCompany) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

var File_PATH_company_svc_proto protoreflect.FileDescriptor

const file_PATH_company_svc_proto_rawDesc = "" +
	"\n" +
	"\x16PATH/company_svc.proto\x12\n" +
	"pb_company\"S\n" +
	"\x0fResponseAnswers\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x120\n" +
	"\acompany\x18\x02 \x01(\v2\x16.pb_company.NewCompanyR\acompany\"\xb2\x01\n" +
	"\x10RequestVariables\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontact\x18\x02 \x01(\tR\acontact\x12\x18\n" +
	"\awebsite\x18\x03 \x01(\tR\awebsite\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12\x10\n" +
	"\x03zip\x18\a \x01(\tR\x03zip\"\xc0\x01\n" +
	"\n" +
	"NewCompany\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acontact\x18\x03 \x01(\tR\acontact\x12\x18\n" +
	"\awebsite\x18\x04 \x01(\tR\awebsite\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12\x10\n" +
	"\x03zip\x18\b \x01(\tR\x03zip2^\n" +
	"\x0eCompanyService\x12L\n" +
	"\rAddNewCompany\x12\x1c.pb_company.RequestVariables\x1a\x1b.pb_company.ResponseAnswers\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_PATH_company_svc_proto_rawDescOnce sync.Once
	file_PATH_company_svc_proto_rawDescData []byte
)

func file_PATH_company_svc_proto_rawDescGZIP() []byte {
	file_PATH_company_svc_proto_rawDescOnce.Do(func() {
		file_PATH_company_svc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PATH_company_svc_proto_rawDesc), len(file_PATH_company_svc_proto_rawDesc)))
	})
	return file_PATH_company_svc_proto_rawDescData
}

var file_PATH_company_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_PATH_company_svc_proto_goTypes = []any{
	(*ResponseAnswers)(nil),  // 0: pb_company.ResponseAnswers
	(*RequestVariables)(nil), // 1: pb_company.RequestVariables
	(*NewCompany)(nil),       // 2: pb_company.NewCompany
}
var file_PATH_company_svc_proto_depIdxs = []int32{
	2, // 0: pb_company.ResponseAnswers.company:type_name -> pb_company.NewCompany
	1, // 1: pb_company.CompanyService.AddNewCompany:input_type -> pb_company.RequestVariables
	0, // 2: pb_company.CompanyService.AddNewCompany:output_type -> pb_company.ResponseAnswers
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_PATH_company_svc_proto_init() }
func file_PATH_company_svc_proto_init() {
	if File_PATH_company_svc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PATH_company_svc_proto_rawDesc), len(file_PATH_company_svc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_PATH_company_svc_proto_goTypes,
		DependencyIndexes: file_PATH_company_svc_proto_depIdxs,
		MessageInfos:      file_PATH_company_svc_proto_msgTypes,
	}.Build()
	File_PATH_company_svc_proto = out.File
	file_PATH_company_svc_proto_goTypes = nil
	file_PATH_company_svc_proto_depIdxs = nil
}
