// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: PATH/my_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyRequest) Reset() {
	*x = MyRequest{}
	mi := &file_PATH_my_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyRequest) ProtoMessage() {}

func (x *MyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PATH_my_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyRequest.ProtoReflect.Descriptor instead.
func (*MyRequest) Descriptor() ([]byte, []int) {
	return file_PATH_my_service_proto_rawDescGZIP(), []int{0}
}

func (x *MyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyResponse) Reset() {
	*x = MyResponse{}
	mi := &file_PATH_my_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyResponse) ProtoMessage() {}

func (x *MyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PATH_my_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyResponse.ProtoReflect.Descriptor instead.
func (*MyResponse) Descriptor() ([]byte, []int) {
	return file_PATH_my_service_proto_rawDescGZIP(), []int{1}
}

func (x *MyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_PATH_my_service_proto protoreflect.FileDescriptor

const file_PATH_my_service_proto_rawDesc = "" +
	"\n" +
	"\x15PATH/my_service.proto\x12\n" +
	"my_service\"\x1f\n" +
	"\tMyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\":\n" +
	"\n" +
	"MyResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2H\n" +
	"\tMyService\x12;\n" +
	"\bMyMethod\x12\x15.my_service.MyRequest\x1a\x16.my_service.MyResponse\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_PATH_my_service_proto_rawDescOnce sync.Once
	file_PATH_my_service_proto_rawDescData []byte
)

func file_PATH_my_service_proto_rawDescGZIP() []byte {
	file_PATH_my_service_proto_rawDescOnce.Do(func() {
		file_PATH_my_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PATH_my_service_proto_rawDesc), len(file_PATH_my_service_proto_rawDesc)))
	})
	return file_PATH_my_service_proto_rawDescData
}

var file_PATH_my_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_PATH_my_service_proto_goTypes = []any{
	(*MyRequest)(nil),  // 0: my_service.MyRequest
	(*MyResponse)(nil), // 1: my_service.MyResponse
}
var file_PATH_my_service_proto_depIdxs = []int32{
	0, // 0: my_service.MyService.MyMethod:input_type -> my_service.MyRequest
	1, // 1: my_service.MyService.MyMethod:output_type -> my_service.MyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PATH_my_service_proto_init() }
func file_PATH_my_service_proto_init() {
	if File_PATH_my_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PATH_my_service_proto_rawDesc), len(file_PATH_my_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_PATH_my_service_proto_goTypes,
		DependencyIndexes: file_PATH_my_service_proto_depIdxs,
		MessageInfos:      file_PATH_my_service_proto_msgTypes,
	}.Build()
	File_PATH_my_service_proto = out.File
	file_PATH_my_service_proto_goTypes = nil
	file_PATH_my_service_proto_depIdxs = nil
}
